### ISSUE TITLE
Write an installation startup section for README.md

### ISSUE THREAD

**Issue by Kielan** [birkir/hekla#7]
#5 similar issue there is no ios or android set up and installation guide

suggestion

step 1 yarn install
separate android and ios setup
firebase for respective devices
also missing Podfile.lock and Manifest.lock on ios version

any other set up steps?

**Comment by birkir** [comment]
Good call. This project is not exactly targeted at beginners, even though it might be with proper documentation. Seasoned RN developers should be able to get this up and running without any problems given a Firebase guide, I'll add that to the readme.

I don't check in `Podfile.lock` because every version update of cocoapods has been breaking it in the past. I don't want to require a specific version of cocoapods.

**Comment by Kielan** [comment]
As a (semi-seasoned maybe?) React Native developer definitely would encourage not using podfiles as they are almost impossible to maintain in a react native app.

**Comment by birkir** [comment]
Closed with #96341bb
